#!/usr/bin/env bash
#Install and configure HAproxy

sudo apt update -y
sudo apt install haproxy -y
config=\
"backend my_servers
        balance roundrobin
        server 5731-web-01 54.167.62.171
        server 5731-web-02 54.89.71.99
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
