#!/usr/bin/env bash
# script to install nginx on your web-01 server
sudo apt-get update -y 
sudo apt-get install -y nginx
sudo echo "Holberton School" > /var/www/index.html
sudo service nginx restart
