#!/usr/bin/env bash
# configure nginx server
sudo apt update
sudo apt install nginx -y
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/server_name _;\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" 
sudo sed -i "53i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
